openapi: 3.1.0
info:
  title: Authentication API
  description: User authentication and profile management endpoints for Physical AI Textbook
  version: 1.0.0
  contact:
    name: Authentication Service
servers:
  - url: http://localhost:8000/api/v1
    description: Local development
  - url: https://api.yourdomain.com/api/v1
    description: Production

tags:
  - name: Authentication
    description: User registration, login, logout operations
  - name: Profile
    description: User profile management
  - name: Password
    description: Password reset operations

paths:
  /auth/register:
    post:
      tags: [Authentication]
      summary: Register new user
      description: Create a new user account with email/password and learning profile
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          $ref: '#/components/responses/RateLimited'

  /auth/login:
    post:
      tags: [Authentication]
      summary: User login
      description: Authenticate user and create session
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          $ref: '#/components/responses/RateLimited'

  /auth/logout:
    post:
      tags: [Authentication]
      summary: User logout
      description: Invalidate current session
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out successfully
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auth/me:
    get:
      tags: [Authentication]
      summary: Get current user
      description: Retrieve currently authenticated user information
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /profile:
    get:
      tags: [Profile]
      summary: Get user profile
      description: Retrieve learning profile for authenticated user
      operationId: getProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      tags: [Profile]
      summary: Update user profile
      description: Update learning profile fields
      operationId: updateProfile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdateRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningProfile'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auth/forgot-password:
    post:
      tags: [Password]
      summary: Request password reset
      description: Send password reset email to user
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Reset email sent (generic message for security)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: If the email exists, a password reset link has been sent
        '429':
          $ref: '#/components/responses/RateLimited'

  /auth/reset-password:
    post:
      tags: [Password]
      summary: Reset password
      description: Complete password reset with token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password reset successfully
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required: [email, password, name, skill_level]
      properties:
        email:
          type: string
          format: email
          maxLength: 255
          example: learner@example.com
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 128
          example: SecurePass123!
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: John Doe
        skill_level:
          $ref: '#/components/schemas/SkillLevel'
        learning_goals:
          type: string
          maxLength: 5000
          example: Master ROS 2 navigation and build autonomous robots
        prior_experience:
          type: string
          maxLength: 5000
          example: 2 years Python, basic understanding of robotics

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: learner@example.com
        password:
          type: string
          format: password
          example: SecurePass123!
        remember_me:
          type: boolean
          default: false
          description: Extend session to 30 days

    ProfileUpdateRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        skill_level:
          $ref: '#/components/schemas/SkillLevel'
        learning_goals:
          type: string
          maxLength: 5000
        prior_experience:
          type: string
          maxLength: 5000

    ForgotPasswordRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email
          example: learner@example.com

    ResetPasswordRequest:
      type: object
      required: [token, new_password]
      properties:
        token:
          type: string
          description: Password reset token from email
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        new_password:
          type: string
          format: password
          minLength: 8
          maxLength: 128
          example: NewSecurePass456!

    AuthResponse:
      type: object
      required: [access_token, token_type, user]
      properties:
        access_token:
          type: string
          description: JWT access token
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
        token_type:
          type: string
          enum: [bearer]
        user:
          $ref: '#/components/schemas/UserProfile'

    UserProfile:
      type: object
      required: [id, email, created_at, learning_profile]
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        email:
          type: string
          format: email
          example: learner@example.com
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        last_login_at:
          type: string
          format: date-time
          nullable: true
        learning_profile:
          $ref: '#/components/schemas/LearningProfile'

    LearningProfile:
      type: object
      required: [id, user_id, name, skill_level, created_at, updated_at]
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        name:
          type: string
          example: John Doe
        skill_level:
          $ref: '#/components/schemas/SkillLevel'
        learning_goals:
          type: string
          nullable: true
          example: Master ROS 2 navigation
        prior_experience:
          type: string
          nullable: true
          example: 2 years Python experience
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    SkillLevel:
      type: string
      enum: [beginner, intermediate, advanced]
      example: beginner

    Error:
      type: object
      required: [detail]
      properties:
        detail:
          type: string
          example: Invalid credentials
        error_code:
          type: string
          example: AUTH_001

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    RateLimited:
      description: Too many requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: Rate limit exceeded. Try again in 15 minutes.
            error_code: RATE_LIMIT_001
